<script setup lang="ts">
import {ref,computed} from 'vue'
import {pinhole} from '../utils/learningMath'
const props=withDefaults(defineProps<{mode?:string}>(),{mode:'mesh'})
const baseline=ref(1.2),labeled=ref(true),threshold=ref(.75)
const corners=[[-1,-.6,5],[1,-.6,5],[1,.6,5],[-1,.6,5]],confs=[.97,.93,.89,.83,.78,.72,.64,.57],truth=[true,true,true,false,true,false,true,false]
const project=(k:number)=>corners.map(p=>pinhole([p[0]+(k-1)*baseline.value,p[1],p[2]],190,190,125,115).join(',')).join(' ')
const selected=computed(()=>confs.map((p,i)=>p>=threshold.value?i:-1).filter(i=>i>=0))
</script>
<template><template v-if="mode==='mesh'"><svg class="lab-svg" viewBox="0 0 840 265" role="img" aria-label="Une annotation 3D reprojetée dans trois vues"><g v-for="k in [0,1,2]" :key="k" :transform="`translate(${k*280},0)`"><rect x="8" y="25" width="262" height="210" fill="#e7eef1"/><polygon :points="project(k)" :fill="labeled?'#25B34B':'#a1b4bf'" style="opacity:.6" stroke="#334155" stroke-width="2"/><line x1="15" y1="215" x2="260" y2="215" stroke="#94a3b8"/><text x="135" y="49" text-anchor="middle">Vue {{k+1}}</text><text x="135" y="255" text-anchor="middle">Caméra x = {{((1-k)*baseline).toFixed(1)}} m</text></g></svg><div class="lab-controls"><label><input aria-label="Annotation du maillage" v-model="labeled" type="checkbox"/>Annoter l’objet une fois en 3D</label><label>Écart entre caméras<input aria-label="Écart caméras" v-model.number="baseline" type="range" min="0" max="2.5" step=".1"/></label></div><p class="lab-caption">Même maillage et poses connues → labels dans plusieurs images. Un test de visibilité doit éliminer les surfaces occultées.</p></template>
<template v-else><div class="lab-grid"><svg class="lab-svg" viewBox="0 0 510 265" role="img" aria-label="Sélection des pseudo-étiquettes"><g v-for="(p,i) in confs" :key="i" :transform="`translate(${35+(i%4)*125},${35+Math.floor(i/4)*120})`"><rect width="95" height="75" rx="5" :fill="p>=threshold?'#e7f5eb':'#e2e8f0'" :stroke="p>=threshold?'#218638':'#94a3b8'" stroke-width="2"/><path d="M20 50L45 20L72 50Z" fill="#789baa"/><text x="47" y="95" text-anchor="middle">p = {{p.toFixed(2)}}</text><text v-if="p>=threshold" x="47" y="64" text-anchor="middle" class="small">{{truth[i]?'correct':'erroné'}}</text></g></svg><div class="lab-readout"><p><strong>{{selected.length}}</strong> pseudo-étiquettes retenues</p><p>{{selected.filter(i=>truth[i]).length}} correctes ; {{selected.filter(i=>!truth[i]).length}} erronées</p><p>Le seuil règle le compromis quantité / bruit.</p><p>Une prédiction confiante peut être fausse.</p></div></div><div class="lab-controls"><label>Seuil de confiance<input aria-label="Seuil pseudo-étiquettes" v-model.number="threshold" type="range" min=".5" max="1" step=".01"/>{{threshold.toFixed(2)}}</label><span>Vérité connue seulement dans cette simulation.</span></div></template></template>
