<script setup lang="ts">
import {ref,computed} from 'vue'
import {network} from '../utils/learningMath'
const theta=ref([.6,.2,.8,.1]),x=ref(1),y=ref(2),eta=ref(.1),step=ref(3),updates=ref(0)
const net=computed(()=>network(theta.value,x.value,y.value)),labels=['Entrée','Préactivation','Activation tanh','Prédiction','Perte'],nodes=computed(()=>[x.value,net.value.a,net.value.h,net.value.prediction,net.value.loss])
const update=()=>{theta.value=theta.value.map((v,i)=>v-eta.value*net.value.gradient[i]);updates.value++;step.value=0}
</script>
<template><svg class="lab-svg" style="height:175px" viewBox="0 0 840 175" role="img" aria-label="Graphe de calcul et propagation des dérivées"><g v-for="(label,i) in labels" :key="label"><line v-if="i<4" :x1="120+i*165" y1="72" :x2="166+i*165" y2="72" stroke="#00BDF2" stroke-width="3"/><rect :x="8+i*165" y="42" width="115" height="60" rx="6" :fill="i===4?'#fff0ef':'white'" :stroke="i===4?'#CF1C24':'#00BDF2'"/><text :x="65+i*165" y="25" text-anchor="middle">{{label}}</text><text :x="65+i*165" y="80" text-anchor="middle" style="font-size:20px">{{nodes[i].toFixed(3)}}</text><text v-if="i<4" :x="65+i*165" y="124" text-anchor="middle" class="small">{{['x','a = w₁x + b₁','h = tanh(a)','ŷ = w₂h + b₂'][i]}}</text></g><g v-if="step>=1"><path d="M720 150H535" fill="none" stroke="#CF1C24" stroke-width="3"/><text x="605" y="169" text-anchor="middle">∂ℓ/∂ŷ = {{net.error.toFixed(3)}}</text></g><g v-if="step>=2"><path d="M535 150H335" fill="none" stroke="#F15A22" stroke-width="3"/><text x="422" y="169" text-anchor="middle">∂ℓ/∂h = {{net.dh.toFixed(3)}}</text></g><g v-if="step>=3"><path d="M335 150H170" fill="none" stroke="#218638" stroke-width="3"/><text x="240" y="169" text-anchor="middle">∂ℓ/∂a = {{net.da.toFixed(3)}}</text></g></svg>
<div class="lab-grid" style="grid-template-columns:1fr 1.25fr"><div class="lab-readout"><b>Paramètres [w₁, b₁, w₂, b₂]</b><p>{{theta.map(v=>v.toFixed(3)).join(' ; ')}}</p><b v-if="step>=3">Gradient : {{net.gradient.map(v=>v.toFixed(3)).join(' ; ')}}</b></div><div class="lab-readout"><b>{{['Calcul avant','Dériver la perte','Traverser la sortie','Appliquer la règle de chaîne'][step]}}</b><p>{{['Les paramètres produisent une prédiction, puis une erreur.','Pour ℓ = (ŷ − y)²/2, la dérivée vaut ŷ − y.','Multiplier par w₂ pour remonter de ŷ à h.','Multiplier par 1 − h², puis par x pour obtenir ∂ℓ/∂w₁.'][step]}}</p></div></div>
<div class="lab-controls" style="margin-top:9px"><button @click="step=(step+1)%4">Étape</button><button class="primary" @click="update">Mettre à jour θ</button><label>Taux η<input aria-label="Taux réseau" v-model.number="eta" type="range" min=".01" max=".5" step=".01"/>{{eta.toFixed(2)}}</label><span>{{updates}} mise(s) à jour · cible y = 2</span></div>
</template>
