<script setup lang="ts">
import {ref,computed,watch} from 'vue'
import {generalization} from '../utils/learningMath'
const capacity=ref(16),noise=ref(.55),lambda=ref(0),epoch=ref(100),revealed=ref(false),chosen=ref(-1)
const run=computed(()=>generalization(capacity.value,noise.value,lambda.value)),index=computed(()=>Math.min(epoch.value,120)),record=computed(()=>run.value.curves[index.value]),best=computed(()=>run.value.curves.reduce((a,v,i,all)=>v.validation<all[a].validation?i:a,0))
const scale=computed(()=>Math.max(.4,...run.value.curves.map(v=>Math.max(v.train,v.validation,v.test)))*1.08)
const path=(key:string)=>run.value.curves.slice(0,index.value+1).map((v,i)=>`${i?'L':'M'}${42+i*3.7},${220-v[key]/scale.value*190}`).join(' ')
watch([capacity,noise,lambda],()=>{revealed.value=false;chosen.value=-1})
const freeze=()=>{chosen.value=index.value;revealed.value=true}
</script>
<template><div class="lab-grid"><svg class="lab-svg" viewBox="0 0 530 270" role="img" aria-label="Courbes entraînement validation et test"><line x1="42" y1="220" x2="493" y2="220" class="axis"/><line x1="42" y1="28" x2="42" y2="220" class="axis"/><text x="43" y="18">Erreur quadratique moyenne</text><text x="42" y="242">0</text><text x="445" y="242">1 200</text><text x="220" y="264">Époques</text><path :d="path('train')" stroke="#087fa1" class="line"/><path :d="path('validation')" stroke="#F15A22" class="line"/><path v-if="revealed" :d="path('test')" stroke="#218638" stroke-dasharray="5 3" class="line"/><line :x1="42+best*3.7" :x2="42+best*3.7" y1="30" y2="220" stroke="#64748b" stroke-dasharray="3"/><text :x="Math.min(420,Math.max(75,42+best*3.7))" y="38" class="small">Meilleure validation</text></svg><div class="lab-readout" data-testid="generalization"><p style="color:#087fa1">Entraînement : {{record.train.toFixed(3)}}</p><p style="color:#b74416">Validation : {{record.validation.toFixed(3)}}</p><p v-if="revealed" style="color:#218638">Test du modèle choisi : <strong>{{run.curves[chosen].test.toFixed(3)}}</strong></p><p v-else>Test masqué pendant le choix du modèle.</p><p>Arrêt conseillé : époque <b>{{run.curves[best].epoch}}</b>.</p><p v-if="revealed" class="small-note">Courbe de test révélée pour l’analyse pédagogique après le choix.</p></div></div>
<div class="lab-controls"><label>Capacité<input aria-label="Capacité" v-model.number="capacity" type="range" min="3" max="22"/>{{capacity}}</label><label>Bruit<input aria-label="Bruit" v-model.number="noise" type="range" min="0" max=".9" step=".05"/>{{noise.toFixed(2)}}</label><label>λ<input aria-label="Régularisation" v-model.number="lambda" type="range" min="0" max=".15" step=".005"/>{{lambda.toFixed(3)}}</label></div><div class="lab-controls" style="margin-top:7px"><label>Époque<input aria-label="Époque" v-model.number="epoch" type="range" min="0" max="120"/>{{record.epoch}}</label><button @click="epoch=best">Choisir la meilleure validation</button><button class="primary" :disabled="revealed" @click="freeze">Figer puis révéler le test</button></div></template>
