<script setup lang="ts">
import {ref,computed} from 'vue'
const step=ref(0)
const mats=[[[4,1,3],[2,0,5],[3,2,2]],[[3,0,2],[2,0,5],[1,0,0]],[[2,0,2],[1,0,5],[0,0,0]],[[2,0,2],[1,0,5],[0,0,0]],[[1,0,1],[0,0,4],[0,1,0]],[[1,0,1],[0,0,4],[0,1,0]]]
const texts=['Coûts : une ligne par cible, une colonne par prédiction.','Soustraire le minimum de chaque ligne : 1, 0, 2.','Soustraire le minimum de chaque colonne : 1, 0, 0.','Tous les zéros sont couverts par la colonne B et la ligne 3 : seulement deux traits.','Plus petit coût non couvert = 1. Le soustraire hors traits et l’ajouter aux intersections.','Trois zéros indépendants : affectation A←2, B←1, C←3. Coût original : 2 + 1 + 2 = 5.']
const mat=computed(()=>mats[step.value]);const assigned=(r:number,c:number)=>step.value===5&&[1,0,2][r]===c
</script>
<template><div class="demo"><div class="top"><button @click="step=Math.max(0,step-1)" :disabled="step===0">Retour</button><button @click="step=Math.min(5,step+1)" :disabled="step===5">Étape</button><button @click="step=0">Réinitialiser</button></div><div class="body"><table><thead><tr><th>Cible</th><th>A</th><th>B</th><th>C</th></tr></thead><tbody><tr v-for="(row,r) in mat" :key="r"><th>{{r+1}}</th><td v-for="(v,c) in row" :key="c" :class="{chosen:assigned(r,c),covered:step===3&&(r===2||c===1),zero:v===0}">{{v}}</td></tr></tbody></table><div><p>{{texts[step]}}</p><p>Glouton global : choisir d’abord le coût 0 (2,B), puis 2 (3,C), impose 4 (1,A). Total : <b>6</b>.</p><p>Le minimum global vaut <b>5</b>. La minimisation de chaque coût isolé ne minimise pas nécessairement leur somme.</p></div></div></div></template>
<style scoped>.demo{font:17px sans-serif}.top{display:flex;gap:12px}.body{display:grid;grid-template-columns:360px 1fr;gap:30px;margin-top:15px}table{width:100%;text-align:center}td,th{height:55px;border:1px solid #cbd5e1;font-size:23px}.zero{font-weight:bold;color:#CF1C24}.covered{background:#fde8da}.chosen{background:#b1efc0!important;outline:2px solid #25B34B}button{padding:7px 12px;border-radius:5px;background:#e5e7eb}button:disabled{opacity:.4}</style>
