<script setup lang="ts">
import {ref,computed} from 'vue'
import {clamp} from '../utils/learningMath'
import {usePlayback} from '../utils/usePlayback'
const time=ref(4),delay=ref(1.5),yielding=ref(true),topology=ref(true)
const car=(t:number)=>yielding.value?Math.min(330,70+48*t):70+48*t
const pedestrian=(t:number)=>clamp(20+35*Math.max(0,t-delay.value),20,260)
const gap=computed(()=>Math.hypot(car(time.value)-425,160-pedestrian(time.value))/25)
const minGap=computed(()=>Math.min(...Array.from({length:121},(_,i)=>Math.hypot(car(i*.1)-425,160-pedestrian(i*.1))/25)))
const advance=()=>{if(time.value>=12)return false;time.value=Math.min(12,time.value+.1)}, {playing}=usePlayback(advance,80)
</script>
<template><div class="lab-grid"><svg class="lab-svg" viewBox="0 0 580 275" role="img" aria-label="Intersection avec véhicule et piéton"><defs><clipPath id="intersection-viewport"><rect width="580" height="275"/></clipPath></defs><g clip-path="url(#intersection-viewport)"><rect width="580" height="275" fill="#dcebdc"/><path d="M0 95H580V205H0ZM360 0H480V275H360Z" fill="#77838b"/><path d="M0 150H580M420 0V275" stroke="white" stroke-width="2" stroke-dasharray="18 10"/><g v-for="i in 7" :key="i"><rect :x="400" :y="95+i*13" width="48" height="7" fill="white"/></g><path v-if="topology" d="M25 160H530M270 160Q385 160 385 240" fill="none" stroke="#00BDF2" stroke-width="4"/><rect x="397" y="135" width="56" height="48" fill="#F15A22" style="opacity:.25"/><rect :x="car(time)-22" y="150" width="44" height="23" rx="5" fill="#CF1C24"/><circle cx="425" :cy="pedestrian(time)" r="9" fill="#25B34B" stroke="white" stroke-width="2"/><text x="15" y="28">t = {{time.toFixed(1)}} s</text><text x="15" y="259">Zone orange : conflit possible entre trajectoires</text></g></svg><div class="lab-readout" data-testid="intersection"><p><b>Carte</b> : voies, passage piéton, connexions.</p><p><b>Scénario</b> : instants de départ, vitesses et comportement.</p><p>Distance actuelle : {{gap.toFixed(1)}} m</p><p>Minimum sur 12 s : <strong>{{minGap.toFixed(1)}} m</strong></p><p>{{minGap<1?'Trajectoires en conflit.':'Trajectoires séparées dans ce scénario.'}}</p></div></div><div class="lab-controls"><button class="primary" @click="playing=!playing">{{playing?'Pause':'Lecture'}}</button><label>Temps<input aria-label="Temps intersection" v-model.number="time" type="range" min="0" max="12" step=".1"/></label><label>Départ piéton<input aria-label="Départ piéton" v-model.number="delay" type="range" min="0" max="6" step=".1"/></label><label><input aria-label="Céder le passage" type="checkbox" v-model="yielding"/>Céder le passage</label><label><input aria-label="Topologie" type="checkbox" v-model="topology"/>Topologie</label></div></template>
