<script setup lang="ts">
import {ref,computed} from 'vue'
import {regressionLoss,crossEntropy} from '../utils/learningMath'
const props=withDefaults(defineProps<{mode?:string}>(),{mode:'regression'})
const error=ref(1.5),delta=ref(1),scores=ref([2,1,0]),target=ref(props.mode==='classification'?1:0)
const classes=['Route','Piéton','Véhicule']
const ce=computed(()=>crossEntropy(scores.value,target.value)),kinds=['quadratic','absolute','huber'],colors=['#CF1C24','#087fa1','#218638'],names=['Quadratique : e²/2','Absolue : |e|','Huber : δ='+delta.value]
const path=(kind:string)=>Array.from({length:121},(_,i)=>{const e=-3+i*.05,l=regressionLoss(e,kind,delta.value).loss;return `${i?'L':'M'}${40+(e+3)*72},${220-l*38}`}).join(' ')
</script>
<template><div class="lab-grid"><svg class="lab-svg" viewBox="0 0 510 270" role="img" :aria-label="mode==='regression'?'Pertes en fonction de l’erreur':'Probabilités des trois classes'">
<template v-if="mode==='regression'"><line x1="40" y1="220" x2="485" y2="220" class="axis"/><line x1="256" y1="30" x2="256" y2="220" class="axis"/><g v-for="v in [-3,-2,-1,0,1,2,3]" :key="v"><text :x="40+(v+3)*72" y="240" text-anchor="middle">{{v}}</text></g><path v-for="(kind,i) in kinds" :key="kind" :d="path(kind)" :stroke="colors[i]" class="line"/><line :x1="40+(error+3)*72" y1="30" :x2="40+(error+3)*72" y2="220" stroke="#64748b" stroke-dasharray="4"/><circle v-for="(kind,i) in kinds" :key="kind" :cx="40+(error+3)*72" :cy="220-regressionLoss(error,kind,delta).loss*38" r="5" :fill="colors[i]"/><text x="42" y="23">Perte</text><text x="255" y="264" text-anchor="middle">Erreur e = prédiction − cible</text></template>
<template v-else><g v-for="(p,i) in ce.p" :key="i"><rect :x="55+150*i" :y="220-170*p" width="85" :height="170*p" :fill="i===target?'#25B34B':'#00BDF2'"/><text :x="97+150*i" :y="208-170*p" text-anchor="middle">{{(100*p).toFixed(1)}} %</text><text :x="97+150*i" y="243" text-anchor="middle">{{classes[i]}}</text></g><line x1="30" x2="485" y1="220" y2="220" class="axis"/><text x="40" y="25">Probabilités : somme = 1</text></template>
</svg><div class="lab-readout" data-testid="loss-readout"><template v-if="mode==='regression'"><p v-for="(kind,i) in kinds" :key="kind" :style="{borderLeft:'3px solid '+colors[i],paddingLeft:'8px'}">{{['Quadratique','Absolue','Huber'][i]}}<br/><b>ℓ = {{regressionLoss(error,kind,delta).loss.toFixed(3)}}</b><br/>dℓ/de = {{regressionLoss(error,kind,delta).gradient.toFixed(3)}}</p></template><template v-else><p>Cible : <strong>{{classes[target]}}</strong></p><p>Étiquette y = [{{classes.map((_,i)=>Number(i===target)).join(' ; ')}}]</p><p>p(cible) = <b>{{ce.p[target].toFixed(4)}}</b></p><p>ℓ = −ln p(cible) = <strong data-testid="cross-entropy-value">{{ce.loss.toFixed(3)}}</strong></p><p>Gradients des scores : p − y<br/>{{ce.gradient.map(v=>v.toFixed(3)).join(' ; ')}}</p></template></div></div>
<div v-if="mode==='regression'" class="lab-controls"><label>Erreur <input aria-label="Erreur" v-model.number="error" type="range" min="-3" max="3" step=".05"/>{{error.toFixed(2)}}</label><label>Seuil Huber δ <input aria-label="Seuil Huber" v-model.number="delta" type="range" min=".2" max="2" step=".1"/>{{delta.toFixed(1)}}</label></div>
<div v-else class="lab-controls"><label v-for="(_,i) in scores" :key="i">Score {{classes[i]}} : {{scores[i].toFixed(1)}}<input :aria-label="'Score '+i" v-model.number="scores[i]" type="range" min="-4" max="4" step=".1"/></label><select v-model.number="target" aria-label="Classe cible"><option :value="0">Route</option><option :value="1">Piéton</option><option :value="2">Véhicule</option></select></div>
</template>
