<script setup lang="ts">
import {ref,computed} from 'vue'
const height=ref(1.5),objectHeight=ref(0),depth=ref(12)
const fy=190,cy=65,actualHeight=1.5
const v=computed(()=>cy+fy*(actualHeight-objectHeight.value)/depth.value),estimated=computed(()=>Math.abs(v.value-cy)<.001?Infinity:height.value*fy/(v.value-cy))
const project=(x:number,z:number)=>[175+fy*x/z,cy+fy*actualHeight/z]
const lanes=[-3,0,3].map(x=>Array.from({length:15},(_,i)=>project(x,3+i*2).join(',')).join(' '))
const px=(x:number)=>640+x*18,py=(z:number)=>245-z*6
</script>
<template><svg class="lab-svg" style="height:268px" viewBox="0 0 840 268" role="img" aria-label="Éléments de carte projetés de l’image au sol"><rect x="5" y="25" width="365" height="230" fill="#d8e7ee"/><rect x="5" y="65" width="365" height="190" fill="#6d7b86"/><text x="20" y="47">Caméra : lignes convergentes</text><polyline v-for="(line,i) in lanes" :key="i" :points="line" fill="none" stroke="white" stroke-width="3" :stroke-dasharray="i===1?'12 8':'none'"/><line x1="8" y1="65" x2="370" y2="65" stroke="#F15A22" stroke-dasharray="5"/><circle cx="175" :cy="v" r="7" fill="#CF1C24" stroke="white" stroke-width="2"/><text x="20" y="238" style="fill:white">Horizon v₀ = 65 px</text><text x="404" y="135" style="font-size:34px">→</text><rect x="502" y="25" width="288" height="230" fill="#edf2f5"/><line v-for="x in [-3,0,3]" :key="x" :x1="px(x)" :x2="px(x)" y1="45" y2="242" stroke="#64748b" stroke-width="3" :stroke-dasharray="x===0?'12 8':'none'"/><text x="515" y="45">BEV : lignes parallèles</text><circle :cx="px(0)" :cy="py(depth)" r="8" fill="none" stroke="#218638" stroke-width="3"/><circle v-if="estimated>0&&estimated<35" :cx="px(0)" :cy="py(estimated)" r="6" fill="#CF1C24"/><text x="512" y="264" class="small">Vert : position réelle · rouge : plan supposé</text></svg><div class="lab-controls"><label>Hauteur supposée caméra<input aria-label="Hauteur caméra" v-model.number="height" type="range" min=".8" max="2.2" step=".1"/>{{height.toFixed(1)}} m</label><label>Hauteur du point<input aria-label="Hauteur point" v-model.number="objectHeight" type="range" min="0" max="1.5" step=".1"/>{{objectHeight.toFixed(1)}} m</label></div><p class="lab-caption">z estimé = h fᵧ / (v − v₀) = <b>{{Number.isFinite(estimated)?estimated.toFixed(1)+' m':'indéterminé à l’horizon'}}</b>. Le point est réellement à {{depth}} m.</p></template>
