<script setup lang="ts">
import {ref,computed} from 'vue'
import {seeded} from '../utils/learningMath'
const props=withDefaults(defineProps<{mode?:string}>(),{mode:'dropout'})
const rate=ref(.5),trial=ref(4),inference=ref(false),brightness=ref(1),shift=ref(25),joint=ref(true)
const mask=computed(()=>{const rnd=seeded(trial.value);return Array.from({length:6},()=>inference.value||rnd()>=rate.value)})
const outputs=computed(()=>mask.value.map((on,i)=>on?(i+1)/6/(inference.value?1:1-rate.value):0))
</script>
<template><template v-if="mode==='dropout'"><div class="lab-grid"><svg class="lab-svg" viewBox="0 0 530 270" role="img" aria-label="Masque de dropout"><g v-for="(on,i) in mask" :key="i"><line v-for="j in [0,1,2]" :key="j" x1="60" :y1="65+j*70" x2="265" :y2="30+i*41" :stroke="on?'#94a3b8':'#e2e8f0'"/><line x1="265" :y1="30+i*41" x2="470" y2="135" :stroke="on?'#087fa1':'#e2e8f0'" :stroke-width="on?2:1"/><circle cx="265" :cy="30+i*41" r="16" :fill="on?'#00BDF2':'#e2e8f0'"/><text x="265" :y="35+i*41" text-anchor="middle">{{on?'h'+(i+1):'×'}}</text></g><circle v-for="j in [0,1,2]" :key="j" cx="60" :cy="65+j*70" r="17" fill="#25B34B"/><circle cx="470" cy="135" r="22" fill="#F15A22"/><text x="30" y="260">Entrées</text><text x="420" y="260">Sortie</text></svg><div class="lab-readout"><p><strong>{{mask.filter(Boolean).length}} / 6</strong> neurones actifs</p><p>Masque m ∈ {0, 1}</p><p>Entraînement : h̃ = mh/(1−p)</p><p>Inférence : h̃ = h</p><p>Somme des activations : <b>{{outputs.reduce((a,b)=>a+b,0).toFixed(2)}}</b></p></div></div><div class="lab-controls"><label>Taux p<input aria-label="Taux dropout" v-model.number="rate" type="range" min="0" max=".8" step=".1"/>{{rate.toFixed(1)}}</label><button @click="trial++">Nouveau masque</button><label><input aria-label="Inférence" v-model="inference" type="checkbox"/>Inférence</label></div></template>
<template v-else><svg class="lab-svg" viewBox="0 0 840 245" role="img" aria-label="Augmentation cohérente image et annotation"><g v-for="i in [0,1]" :key="i" :transform="`translate(${i*425},0)`"><rect x="10" y="15" width="395" height="210" fill="#d9ebf0"/><g :style="{filter:`brightness(${i?brightness:1})`}"><rect x="10" y="125" width="395" height="100" fill="#adb8bd"/><path d="M205 125L90 225H340L245 125Z" fill="#64748b"/><g :transform="`translate(${i?shift:0},0)`"><rect x="155" y="120" width="105" height="62" rx="8" fill="#CF1C24"/><rect x="171" y="128" width="72" height="24" fill="#93c5d7"/><circle cx="176" cy="183" r="10" fill="#333"/><circle cx="242" cy="183" r="10" fill="#333"/></g></g><rect :x="150+(i&&joint?shift:0)" y="115" width="115" height="80" fill="none" stroke="#25B34B" stroke-width="4"/><text x="20" y="40">{{i?'Image augmentée':'Image et boîte d’origine'}}</text></g></svg><div class="lab-controls"><label>Luminosité<input aria-label="Luminosité" v-model.number="brightness" type="range" min=".3" max="1.6" step=".05"/></label><label>Translation<input aria-label="Translation image" v-model.number="shift" type="range" min="-90" max="90"/>{{shift}} px</label><label><input aria-label="Transformer les étiquettes" v-model="joint" type="checkbox"/>Transformer les étiquettes</label></div><p class="lab-caption"><b>{{joint?'Annotation cohérente.':'Annotation devenue fausse.'}}</b> Une transformation géométrique modifie aussi les boîtes, masques et intrinsèques concernés.</p></template></template>
