<script setup lang="ts">
import {computed,ref,watch} from 'vue'
import {useNav} from '@slidev/client'
import {usePlayback} from '../utils/usePlayback'
import {observedTarget,observedSource,geometricPair,queryExamples,descriptorSearch,distanceImage} from '../utils/correspondence.mjs'
const props=withDefaults(defineProps<{mode?:'pairs'|'search';stage?:number}>(),{mode:'pairs',stage:0})
const nav=useNav(),u=ref(48),v=ref(20),count=ref(0),example=ref('panel')
function reset(){u.value=48;v.value=20;example.value='panel';count.value=props.mode==='search'?(props.stage>=2?3840:props.stage===1?1920:0):0}
reset();const {playing}=usePlayback(()=>{count.value=Math.min(3840,count.value+240);return count.value<3840},reset,150)
watch(()=>props.stage,()=>{playing.value=false;reset()})
const pixel=computed(()=>nav.isPrintMode.value?[48,20]:[u.value,v.value])
const pair=computed(()=>geometricPair(...pixel.value)),scanned=computed(()=>nav.isPrintMode.value?(props.stage>=2?3840:props.stage===1?1920:0):count.value),result=computed(()=>descriptorSearch(...pixel.value,scanned.value)),distance=computed(()=>distanceImage(result.value.query,scanned.value))
function choose(){const p=queryExamples[example.value];u.value=p[0];v.value=p[1];playing.value=false;count.value=props.mode==='search'?(props.stage>=2?3840:props.stage===1?1920:0):0}
function select([x,y]:number[]){u.value=x;v.value=y;playing.value=false;count.value=props.mode==='search'?(props.stage>=2?3840:props.stage===1?1920:0):0}
function play(){if(count.value>=3840)count.value=0;playing.value=!playing.value}
const fmt=(p:number[]|null)=>p?`[${p.map(x=>x.toFixed(2)).join(', ')}]`:'unavailable'
</script>
<template>
 <div class="correspondence-lab" :data-mode="mode" :data-stage="stage" :data-u="pixel[0]" :data-v="pixel[1]" :data-projection="mode==='pairs'?JSON.stringify(pair.projection.uv):null" :data-visible="mode==='pairs'?pair.visible:null" :data-occluded="mode==='pairs'?pair.occluded:null" :data-positive="mode==='pairs'?JSON.stringify(pair.positive):null" :data-negative="mode==='pairs'?JSON.stringify(pair.negative):null" :data-count="scanned" :data-match="JSON.stringify(result.uv)" :data-distance="Number.isFinite(result.distance)?result.distance:null" :data-geometric-input="mode==='pairs'">
  <div v-if="mode==='pairs'" class="correspondence-pairs"><CameraScene point-label-text="Surface point" :point="pair.point" :show-source="stage>=1" :blocked="stage>=1&&pair.occluded?pair.hit?.p:null"/><div><div class="correspondence-pair-images"><GeoImage :image="observedTarget" label="Target Iₜ" :point="pixel" point-color="#25B34B" :selectable="!nav.isPrintMode.value" @select="select"/><GeoImage :image="observedSource" label="Source Iₛ" :point="stage>=1?pair.positive:null" point-color="#25B34B" :alternative="stage>=2?pair.negative:null" alternative-color="#F15A22"/></div><div class="correspondence-legend">Green: same surface point<span v-if="stage>=2"> · orange: different surface point</span></div></div></div>
  <div v-else class="correspondence-search-images"><GeoImage :image="observedTarget" label="Query image Iₜ" :point="pixel" point-color="#25B34B" :selectable="!nav.isPrintMode.value" @select="select"/><GeoImage :image="observedSource" label="Search image Iₛ" :point="stage>=1?result.uv:null" point-color="#25B34B"/><GeoImage v-if="stage>=1" :image="distance" label="Distance · blue is closer" :point="result.uv" point-color="#25B34B"/><div v-else class="descriptor-search-placeholder">Choose a query descriptor<br>ψₜ(uₜ) and a candidate field ψₛ.</div></div>
  <MathLine v-if="mode==='pairs'" :formula="String.raw`p^{c_t}=D_t(\mathbf u_t)K_t^{-1}\widetilde{\mathbf u}_t,\qquad\mathbf u_s=\pi(K_s(R_{c_t}^{c_s}p^{c_t}+t_{c_t}^{c_s}))`" small/>
  <MathLine v-else :formula="String.raw`\mathbf u_s^*=\arg\min_{\mathbf u_s}\|\boldsymbol{\psi}_t(\mathbf u_t)-\boldsymbol{\psi}_s(\mathbf u_s)\|_2`"/>
  <div class="correspondence-readout">{{mode==='pairs'?`uₜ = ${fmt(pixel)} · projected uₛ = ${fmt(pair.projection.uv)} · ${pair.positive?'visible match available':pair.occluded?'occluded: no positive pair':pair.projection.reason}`:`Compared ${scanned} / 3840 descriptors · ${result.uv?`best candidate ${fmt(result.uv)} · distance ${result.distance.toFixed(4)}`:'no candidate compared yet'}`}}</div>
  <div class="ssl-caption">{{mode==='pairs'?stage<2?'Depth and calibrated poses construct training targets; visibility must be checked.':'A nonmatch is a different visible point, not merely another camera view.':stage===0?'Inference inputs are descriptors; no depth, pose, or geometric match enters the search.':stage===1?'Compute candidate distances; gray pixels have not yet been compared.':'Nearest-feature search returns a candidate, not a guarantee of visibility or grasp validity.'}}</div>
  <div v-if="!nav.isPrintMode.value" class="ssl-parameter-controls lab-controls" @click.stop="($event.target as HTMLElement).closest('button')?.blur()"><label>Query example <select aria-label="Correspondence query" v-model="example" @change="choose();($event.target as HTMLElement).blur()"><option value="panel">Visible foreground</option><option value="background">Visible background</option><option value="occluded">Occluded background</option><option v-if="mode==='pairs'" value="outside">Outside source image</option></select></label><template v-if="mode==='search'&&stage>=1"><button @click="playing=false;count=Math.min(3840,count+240)">Step search</button><button class="primary" @click="play">{{playing?'Pause':'Scan descriptors'}}</button></template><button @click="playing=false;reset()">Reset example</button></div>
  <SSLControls/><div class="ssl-disclosure">{{mode==='pairs'?'Computed static-scene geometry · renderer depth illustrates measured/reconstructed training geometry':'Computed descriptor-only search · fixed illustrative features assigned by construction, not trained Dense Object Nets'}}</div>
 </div>
</template>
<style scoped>.correspondence-pairs{display:grid;grid-template-columns:1fr 1fr;gap:22px;align-items:start}.correspondence-pair-images{display:grid;grid-template-columns:1fr 1fr;gap:15px;padding-top:8px}.correspondence-legend{font-size:13px;margin:12px 0;color:#334155}.correspondence-search-images{display:grid;grid-template-columns:repeat(3,1fr);gap:18px;margin:12px 0}.descriptor-search-placeholder{display:flex;align-items:center;justify-content:center;text-align:center;font-size:16px;background:#f8fafc;border:1px dashed #cbd5e1;margin-top:24px}.correspondence-readout{padding:8px 10px;background:#edf8fc;border-left:3px solid #00BDF2;font-size:15px;line-height:1.3}.correspondence-lab .ssl-caption{font-size:16px;margin:9px 0}.correspondence-lab .ssl-parameter-controls{margin:7px 0}</style>
