<script setup lang="ts">
import {useId} from 'vue'
withDefaults(defineProps<{stage?:number}>(),{stage:0})
const id=useId()
</script>
<template>
  <svg class="ssl-svg failure-svg" viewBox="0 0 860 282" role="img" aria-label="False negatives, a background shortcut, and a crop that removes the mug handle">
    <defs><marker :id="`${id}-arrow`" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto"><path d="M0 0L10 5L0 10Z" fill="#334155"/></marker></defs>
    <template v-if="stage<2"><text x="167" y="28" text-anchor="middle">Recorded observation i = 1</text><text x="684" y="28" text-anchor="middle">Recorded observation j = 2</text><foreignObject x="43" y="46" width="248" height="174"><SampleImage/></foreignObject><foreignObject x="560" y="46" width="248" height="174"><SampleImage v-if="stage===0" :sample="1"/><SampleImage v-else false-negative/></foreignObject><path d="M312 128H536" stroke="#c45314" stroke-width="2" stroke-dasharray="6 4"/><text x="425" y="107" text-anchor="middle" class="small">Negative by sample index</text><text x="425" y="175" text-anchor="middle" class="strong">i ≠ j</text><text x="425" y="266" text-anchor="middle">{{stage===0?'The sampling rule knows which record each view came from.':'Two records can depict the same physical mug: a false negative for identity.'}}</text></template>
    <template v-else-if="stage===2"><text x="122" y="28" text-anchor="middle">Two views of i = 1</text><rect x="26" y="48" width="190" height="150" fill="#e8c19f"/><foreignObject x="47" y="68" width="68" height="91"><SampleImage/></foreignObject><foreignObject x="131" y="68" width="68" height="91"><SampleImage :brightness=".85"/></foreignObject><path d="M234 125H301" class="ssl-forward" :marker-end="`url(#${id}-arrow)`"/><rect x="312" y="83" width="218" height="81" rx="4" class="ssl-encoder"/><text x="421" y="113" text-anchor="middle">Background-only encoder</text><text x="421" y="141" text-anchor="middle" class="small">Ignores the mug</text><path d="M542 125H608" class="ssl-forward" :marker-end="`url(#${id}-arrow)`"/><rect x="620" y="92" width="172" height="63" rx="4" fill="#f9eadc" stroke="#b75b1e"/><text x="706" y="119" text-anchor="middle">Views agree</text><text x="706" y="142" text-anchor="middle" class="small">using background color</text><text x="425" y="236" text-anchor="middle">Distinctive backgrounds can identify records without recognizing the object.</text><text x="425" y="263" text-anchor="middle" class="small">Constructed counterexample · no benchmark loss is claimed</text></template>
    <template v-else><text x="167" y="28" text-anchor="middle">Original: handle visible</text><text x="684" y="28" text-anchor="middle">Augmented view: handle absent</text><foreignObject x="43" y="46" width="248" height="174"><SampleImage/></foreignObject><foreignObject x="560" y="46" width="248" height="174"><SampleImage invalid/></foreignObject><path d="M312 128H536" class="ssl-forward" :marker-end="`url(#${id}-arrow)`"/><text x="425" y="106" text-anchor="middle" class="small">Crop</text><text x="425" y="260" text-anchor="middle">Task: locate a grasp on the handle. The paired view removes required evidence.</text></template>
  </svg>
  <SSLControls/>
</template>
<style scoped>.failure-svg{height:282px}</style>
