<script setup lang="ts">
import {ref,computed} from 'vue'
import {graphExample} from '../utils/learningMath'
const props=withDefaults(defineProps<{mode?:string}>(),{mode:'loop'})
const sigma=ref(.5),bad=ref(false),enabled=ref(true),iterations=ref(6)
const graph=computed(()=>graphExample(enabled.value?props.mode:'none',sigma.value,bad.value,iterations.value)),x=(v:number)=>75+v*42,y=(v:number)=>220-v*34
const path=(p:number[][])=>p.map((p,i)=>`${i?'L':'M'}${x(p[0])},${y(p[1])}`).join(' ')
</script>
<template><div class="lab-grid"><svg class="lab-svg" viewBox="0 0 530 270" role="img" :aria-label="mode==='loop'?'Graphe avec fermeture de boucle':'Graphe avec ancrage géographique'"><path :d="path(graph.truth)" stroke="#cbd5e1" stroke-width="7" fill="none"/><path :d="path(graph.before)" stroke="#F15A22" stroke-dasharray="6 4" class="line"/><path :d="path(graph.after)" stroke="#087fa1" class="line"/><g v-for="(p,i) in graph.after" :key="i"><circle :cx="x(p[0])" :cy="y(p[1])" r="8" :fill="i===0?'#333':'#087fa1'"/><text :x="x(p[0])+12" :y="y(p[1])-12">T{{i}}</text><rect v-if="i>0" :x="(x(p[0])+x(graph.after[i-1][0]))/2-4" :y="(y(p[1])+y(graph.after[i-1][1]))/2-4" width="8" height="8" fill="#087fa1"/></g><g v-if="enabled&&mode==='loop'"><path :d="`M${x(graph.after[0][0])},${y(graph.after[0][1])} Q${10},${120} ${x(graph.after.at(-1)![0])},${y(graph.after.at(-1)![1])}`" fill="none" stroke="#CF1C24" stroke-width="3"/><rect x="31" y="151" width="12" height="12" fill="#CF1C24"/></g><g v-if="enabled&&mode==='gnss'"><circle :cx="x(graph.geo[0])" :cy="y(graph.geo[1])" :r="sigma*34" fill="none" stroke="#218638" stroke-dasharray="4"/><path :d="`M${x(graph.geo[0])-9},${y(graph.geo[1])}h18m-9,-9v18`" stroke="#218638" stroke-width="3"/><line :x1="x(graph.geo[0])" :y1="y(graph.geo[1])" :x2="x(graph.after.at(-1)![0])" :y2="y(graph.after.at(-1)![1])" stroke="#218638" stroke-width="3"/></g><text x="20" y="257">Orange : odométrie · bleu : poses optimisées · T₀ fixé</text></svg><div class="lab-readout" data-testid="factor-graph"><p>{{mode==='loop'?'Facteur relatif entre T₀ et T₅.':'Facteur de position sur T₅.'}}</p><p>Coût pondéré :<br/><b>{{graph.history[0].toFixed(2)}} → {{graph.history.at(-1)!.toFixed(2)}}</b></p><p>Résidu :<br/><strong>{{graph.residual.map(v=>v.toFixed(3)).join(' ; ')}}</strong></p><p>{{bad?'Une mauvaise association peut déformer toute la trajectoire.':'La correction se répartit selon les incertitudes.'}}</p><p class="small-note">Illustration SE(2) ; formulation du cours en SE(3).</p></div></div><div class="lab-controls"><label><input aria-label="Activer facteur" v-model="enabled" type="checkbox"/>Activer le facteur</label><label>σ position<input aria-label="Incertitude facteur" v-model.number="sigma" type="range" min=".15" max="2" step=".05"/>{{sigma.toFixed(2)}} m</label><label><input aria-label="Mauvaise association" v-model="bad" type="checkbox"/>Mauvaise association</label><button @click="iterations=Math.min(iterations+1,12)">Itération</button></div></template>
