<script setup lang="ts">
import {ref,computed} from 'vue'
import {triplet,contrastive,clamp} from '../utils/learningMath'
const props=withDefaults(defineProps<{mode?:string}>(),{mode:'triplet'})
const points=ref([[.8,1.3],[2.9,1.9],[2.1,.6]]),margin=ref(1),positive=ref(true),moving=ref(-1),updates=ref(0)
const result=computed(()=>triplet(...points.value as [number[],number[],number[]],margin.value)),pair=computed(()=>contrastive(points.value[0],points.value[1],positive.value,margin.value))
const sx=(x:number)=>40+x*100,sy=(y:number)=>230-y*75
const move=(event:PointerEvent)=>{if(moving.value<0)return;const svg=event.currentTarget as SVGSVGElement;const matrix=svg.getScreenCTM();if(!matrix)return;const local=new DOMPoint(event.clientX,event.clientY).matrixTransform(matrix.inverse());points.value[moving.value]=[clamp((local.x-40)/100,.05,4.6),clamp((230-local.y)/75,.05,2.6)]}
const step=()=>{if(props.mode==='triplet'){points.value=points.value.map((p,i)=>p.map((v,k)=>v-.1*result.value.gradient[i][k]));updates.value++}else{const a=points.value[0],p=points.value[1],d=Math.hypot(a[0]-p[0],a[1]-p[1]),factor=positive.value?2: d<margin.value?-2*(margin.value-d)/Math.max(d,1e-8):0,g=a.map((v,k)=>factor*(v-p[k]));points.value[0]=a.map((v,k)=>v-.08*g[k]);points.value[1]=p.map((v,k)=>v+.08*g[k]);updates.value++}}
</script>
<template><div class="lab-grid"><svg class="lab-svg" viewBox="0 0 530 270" role="img" aria-label="Espace de représentation manipulable" @pointermove="move" @pointerup="moving=-1" @pointerleave="moving=-1" style="touch-action:none"><line x1="40" x2="510" y1="230" y2="230" class="axis"/><line x1="40" x2="40" y1="20" y2="230" class="axis"/><line v-for="i in (mode==='triplet'?[1,2]:[1])" :key="i" :x1="sx(points[0][0])" :y1="sy(points[0][1])" :x2="sx(points[i][0])" :y2="sy(points[i][1])" :stroke="i===1?'#218638':'#CF1C24'" stroke-width="2" stroke-dasharray="6 3"/><g v-for="i in (mode==='triplet'?[0,1,2]:[0,1])" :key="i" @pointerdown.prevent="moving=i" style="cursor:grab"><circle :cx="sx(points[i][0])" :cy="sy(points[i][1])" r="12" :fill="['#087fa1','#218638','#CF1C24'][i]"/><text :x="sx(points[i][0])+16" :y="sy(points[i][1])-12">{{i===1&&mode==='contrastive'?(positive?'Positif':'Négatif'):['Ancre','Positif','Négatif'][i]}}</text></g><text x="40" y="260">Déplacer les points, puis appliquer un pas de gradient.</text></svg><div class="lab-readout" data-testid="metric"><template v-if="mode==='triplet'"><p>d(a,p) = {{result.dap.toFixed(3)}}</p><p>d(a,n) = {{result.dan.toFixed(3)}}</p><p>ℓ = max(0, d(a,p) − d(a,n) + m)</p><p><strong>ℓ = {{result.loss.toFixed(3)}}</strong></p><p>{{result.loss>0?'La contrainte de marge est violée.':'Marge satisfaite : gradient nul.'}}</p></template><template v-else><p>Paire {{positive?'positive':'négative'}}</p><p>d = {{result.dap.toFixed(3)}}</p><p><strong>ℓ = {{pair.toFixed(3)}}</strong></p><p>{{positive?'Rapprocher les deux représentations.':'Éloigner jusqu’à la marge.'}}</p></template></div></div><div class="lab-controls"><button class="primary" @click="step">Pas de gradient</button><label>Marge<input aria-label="Marge métrique" v-model.number="margin" type="range" min=".1" max="3" step=".1"/>{{margin.toFixed(1)}}</label><label v-if="mode==='contrastive'"><input aria-label="Paire positive" v-model="positive" type="checkbox"/>Paire positive</label><span>{{updates}} mise(s) à jour</span></div></template>
