<script setup lang="ts">
import {ref,computed} from 'vue'
import {quaternionMatrix,mv,pinhole} from '../utils/learningMath'
const props=withDefaults(defineProps<{mode?:string}>(),{mode:'box'})
const yaw=ref(30),pitch=ref(15),depth=ref(6),offset=ref(.4),vertical=ref(0),roll=ref(0),length=ref(2.4),height=ref(1.4),width=ref(1.5)
const R=computed(()=>{const a=yaw.value*Math.PI/360,b=pitch.value*Math.PI/360,c=roll.value*Math.PI/360,cy=Math.cos(a),sy=Math.sin(a),cx=Math.cos(b),sx=Math.sin(b),cz=Math.cos(c),sz=Math.sin(c);return quaternionMatrix([cy*cx*cz+sy*sx*sz,cy*sx*cz+sy*cx*sz,sy*cx*cz-cy*sx*sz,cy*cx*sz-sy*sx*cz])})
const vertices=computed(()=>Array.from({length:8},(_,i)=>[(i&1?1:-1)*length.value/2,(i&2?1:-1)*height.value/2,(i&4?1:-1)*width.value/2]))
const transformed=computed(()=>vertices.value.map(p=>mv(R.value,p).map((v,i)=>v+[offset.value,vertical.value,depth.value][i])))
const uv=computed(()=>transformed.value.map(p=>pinhole(p,205,205,195,125)))
const edges=Array.from({length:8},(_,i)=>[1,2,4].filter(b=>!(i&b)).map(b=>[i,i|b])).flat()
const screen=(p:number[])=>{const dz=(p[2]-depth.value)*20;return [620+p[0]*35-dz,140+p[1]*30-dz]}
const cloud=computed(()=>{const out:number[][]=[];for(let face=0;face<3;face++)for(let i=0;i<8;i++)for(let j=0;j<8;j++){const p=[-length.value/2+length.value*i/7,-height.value/2+height.value*j/7,-width.value/2];if(face===1)p[0]=length.value/2,p[2]=-width.value/2+width.value*i/7;if(face===2)p[1]=-height.value/2,p[2]=-width.value/2+width.value*j/7;out.push(mv(R.value,p).map((v,k)=>v+[offset.value,vertical.value,depth.value][k]))}return out})
const axes=computed(()=>[0,1,2].map(k=>{const p=[0,0,0];p[k]=1.8;return mv(R.value,p).map((v,i)=>v+[offset.value,vertical.value,depth.value][i])}))
</script>
<template><svg class="lab-svg" style="height:250px" viewBox="0 0 840 265" role="img" aria-label="Objet 3D et projections liées"><rect x="10" y="10" width="385" height="232" fill="#e6eef1"/><text x="23" y="32">Projection caméra : image + profondeur</text><g v-for="(p,i) in cloud" :key="i"><circle :cx="pinhole(p,205,205,195,125)[0]" :cy="pinhole(p,205,205,195,125)[1]" r="2.8" :fill="`hsl(${200-p[2]*10},65%,52%)`"/></g><line v-for="([a,b],i) in edges" :key="i" :x1="uv[a][0]" :y1="uv[a][1]" :x2="uv[b][0]" :y2="uv[b][1]" stroke="#CF1C24" stroke-width="2"/><text x="435" y="32">Vue 3D du nuage et de la boîte</text><g v-for="(p,i) in cloud" :key="i"><circle :cx="screen(p)[0]" :cy="screen(p)[1]" r="2.1" fill="#087fa1" style="opacity:.65"/></g><line v-for="([a,b],i) in edges" :key="i" :x1="screen(transformed[a])[0]" :y1="screen(transformed[a])[1]" :x2="screen(transformed[b])[0]" :y2="screen(transformed[b])[1]" stroke="#CF1C24" stroke-width="2"/><g v-if="mode==='pose'" v-for="(a,k) in axes" :key="k"><line :x1="screen([offset,vertical,depth])[0]" :y1="screen([offset,vertical,depth])[1]" :x2="screen(a)[0]" :y2="screen(a)[1]" :stroke="['#CF1C24','#218638','#087fa1'][k]" stroke-width="4"/><text :x="screen(a)[0]+7" :y="screen(a)[1]">{{['x','y','z'][k]}}</text></g><text x="438" y="249">Centre : ({{offset.toFixed(1)}}, {{vertical.toFixed(1)}}, {{depth.toFixed(1)}}) m</text><text x="23" y="259">Dimensions : {{length.toFixed(1)}} × {{height.toFixed(1)}} × {{width.toFixed(1)}} m</text></svg><div class="lab-controls object-controls"><label>Rotation y<input aria-label="Rotation objet" v-model.number="yaw" type="range" min="-180" max="180"/>{{yaw}}°</label><label>Profondeur<input aria-label="Profondeur objet" v-model.number="depth" type="range" min="4" max="12" step=".1"/></label><label v-if="mode==='box'">Longueur<input aria-label="Longueur objet" v-model.number="length" type="range" min="1" max="3.5" step=".1"/></label><label v-else>Inclinaison<input aria-label="Inclinaison objet" v-model.number="pitch" type="range" min="-80" max="80"/></label></div><div class="lab-controls object-controls" style="margin-top:7px"><label>Translation latérale<input aria-label="Translation objet" v-model.number="offset" type="range" min="-1.2" max="1.2" step=".1"/></label><label v-if="mode==='pose'">Translation verticale<input aria-label="Translation verticale" v-model.number="vertical" type="range" min="-1" max="1" step=".1"/></label><label v-if="mode==='pose'">Rotation z<input aria-label="Rotation z" v-model.number="roll" type="range" min="-90" max="90"/></label><label v-if="mode==='box'">Hauteur<input aria-label="Hauteur boîte" v-model.number="height" type="range" min=".7" max="2" step=".1"/></label><label v-if="mode==='box'">Largeur<input aria-label="Largeur 3D" v-model.number="width" type="range" min=".8" max="2.2" step=".1"/></label></div></template>

<style scoped>.object-controls{display:grid;grid-template-columns:repeat(3,1fr);gap:5px}.object-controls label{font-size:13px;justify-content:space-between}.object-controls input[type=range]{width:85px}</style>
