<script setup lang="ts">
import {computed,ref,watch} from 'vue'
import {useNav} from '@slidev/client'
import {usePlayback} from '../utils/usePlayback'
import {observedTarget,observedSource,geometricPair,queryExamples,descriptorSearch,distanceImage} from '../utils/correspondence.mjs'
const props=withDefaults(defineProps<{mode?:'pairs'|'search';stage?:number}>(),{mode:'pairs',stage:0})
const nav=useNav(),u=ref(48),v=ref(20),count=ref(0),example=ref('panel')
function reset(){u.value=48;v.value=20;example.value='panel';count.value=props.mode==='search'?(props.stage>=2?3840:props.stage===1?1920:0):0}
reset();const {playing}=usePlayback(()=>{count.value=Math.min(3840,count.value+240);return count.value<3840},reset,150)
watch(()=>props.stage,()=>{playing.value=false;reset()})
const pixel=computed(()=>nav.isPrintMode.value?[48,20]:[u.value,v.value])
const pair=computed(()=>geometricPair(...pixel.value)),scanned=computed(()=>nav.isPrintMode.value?(props.stage>=2?3840:props.stage===1?1920:0):count.value),result=computed(()=>descriptorSearch(...pixel.value,scanned.value)),distance=computed(()=>distanceImage(result.value.query,scanned.value))
function choose(){const p=queryExamples[example.value];u.value=p[0];v.value=p[1];playing.value=false;count.value=props.mode==='search'?(props.stage>=2?3840:props.stage===1?1920:0):0}
function select([x,y]:number[]){u.value=x;v.value=y;playing.value=false;count.value=props.mode==='search'?(props.stage>=2?3840:props.stage===1?1920:0):0}
function play(){if(count.value>=3840)count.value=0;playing.value=!playing.value}
const fmt=(p:number[]|null)=>p?`[${p.map(x=>x.toFixed(2)).join(', ')}]`:'unavailable'
</script>
<template>
 <div class="correspondence-lab" :data-mode="mode" :data-stage="stage" :data-u="pixel[0]" :data-v="pixel[1]" :data-projection="mode==='pairs'?JSON.stringify(pair.projection.uv):null" :data-visible="mode==='pairs'?pair.visible:null" :data-occluded="mode==='pairs'?pair.occluded:null" :data-positive="mode==='pairs'?JSON.stringify(pair.positive):null" :data-negative="mode==='pairs'?JSON.stringify(pair.negative):null" :data-count="scanned" :data-match="JSON.stringify(result.uv)" :data-distance="Number.isFinite(result.distance)?result.distance:null" :data-geometric-input="mode==='pairs'">
  <div v-if="mode==='pairs'" class="correspondence-pairs"><CameraScene point-label-text="Point de surface" :point="pair.point" :show-source="stage>=1" :blocked="stage>=1&&pair.occluded?pair.hit?.p:null"/><div><div class="correspondence-pair-images"><GeoImage :image="observedTarget" label="Cible Iₜ" :point="pixel" point-color="#25B34B" :selectable="!nav.isPrintMode.value" @select="select"/><GeoImage :image="observedSource" label="Source Iₛ" :point="stage>=1?pair.positive:null" point-color="#25B34B" :alternative="stage>=2?pair.negative:null" alternative-color="#F15A22"/></div><div class="correspondence-legend">Vert : même point de surface<span v-if="stage>=2"> · orange : autre point de surface</span></div></div></div>
  <div v-else class="correspondence-search-images"><GeoImage :image="observedTarget" label="Image requête Iₜ" :point="pixel" point-color="#25B34B" :selectable="!nav.isPrintMode.value" @select="select"/><GeoImage :image="observedSource" label="Image de recherche Iₛ" :point="stage>=1?result.uv:null" point-color="#25B34B"/><GeoImage v-if="stage>=1" :image="distance" label="Distance · bleu : proche" :point="result.uv" point-color="#25B34B"/><div v-else class="descriptor-search-placeholder">Choisir un descripteur requête<br>ψₜ(uₜ) et champ candidat ψₛ.</div></div>
  <MathLine v-if="mode==='pairs'" :formula="String.raw`p^{c_t}=D_t(\mathbf u_t)K_t^{-1}\widetilde{\mathbf u}_t,\qquad\mathbf u_s=\pi(K_s(R_{c_t}^{c_s}p^{c_t}+t_{c_t}^{c_s}))`" small/>
  <MathLine v-else :formula="String.raw`\mathbf u_s^*=\arg\min_{\mathbf u_s}\|\boldsymbol{\psi}_t(\mathbf u_t)-\boldsymbol{\psi}_s(\mathbf u_s)\|_2`"/>
  <div class="correspondence-readout">{{mode==='pairs'?`uₜ = ${fmt(pixel)} · projeté uₛ = ${fmt(pair.projection.uv)} · ${pair.positive?'correspondance visible disponible':pair.occluded?'occulté : aucune paire positive':({"Behind source camera":"Derrière la caméra source","Outside source image":"Hors image source","In bounds":"Dans l’image"})[pair.projection.reason]||pair.projection.reason}`:`Comparés ${scanned} / 3840 descripteurs · ${result.uv?`meilleur candidat ${fmt(result.uv)} · distance ${result.distance.toFixed(4)}`:'aucun candidat comparé'}`}}</div>
  <div class="ssl-caption">{{mode==='pairs'?stage<2?'Profondeur et poses étalonnées construisent les cibles; vérifier la visibilité.':'Une non-correspondance est un autre point visible, pas une autre vue du même point.':stage===0?'La recherche reçoit des descripteurs, sans profondeur, pose ni correspondance géométrique.':stage===1?'Calculer les distances; les pixels gris ne sont pas encore comparés.':'Le plus proche descripteur fournit un candidat, sans garantir visibilité ni prise valide.'}}</div>
  <div v-if="!nav.isPrintMode.value" class="ssl-parameter-controls lab-controls" @click.stop="($event.target as HTMLElement).closest('button')?.blur()"><label>Exemple de requête <select aria-label="Requête de correspondance" v-model="example" @change="choose();($event.target as HTMLElement).blur()"><option value="panel">Avant-plan visible</option><option value="background">Fond visible</option><option value="occluded">Fond occulté</option><option v-if="mode==='pairs'" value="outside">Hors image source</option></select></label><template v-if="mode==='search'&&stage>=1"><button @click="playing=false;count=Math.min(3840,count+240)">Avancer la recherche</button><button class="primary" @click="play">{{playing?'Pause':'Parcourir les descripteurs'}}</button></template><button @click="playing=false;reset()">Réinitialiser l’exemple</button></div>
  <SSLControls/><div class="ssl-disclosure">{{mode==='pairs'?'Scène statique calculée · profondeur du moteur illustrant la géométrie de mesure/reconstruction':'Recherche par descripteurs calculée · caractéristiques illustratives construites, sans Dense Object Nets entraîné'}}</div>
 </div>
</template>
<style scoped>.correspondence-pairs{display:grid;grid-template-columns:1fr 1fr;gap:22px;align-items:start}.correspondence-pair-images{display:grid;grid-template-columns:1fr 1fr;gap:15px;padding-top:8px}.correspondence-legend{font-size:13px;margin:12px 0;color:#334155}.correspondence-search-images{display:grid;grid-template-columns:repeat(3,1fr);gap:18px;margin:12px 0}.descriptor-search-placeholder{display:flex;align-items:center;justify-content:center;text-align:center;font-size:16px;background:#f8fafc;border:1px dashed #cbd5e1;margin-top:24px}.correspondence-readout{padding:8px 10px;background:#edf8fc;border-left:3px solid #00BDF2;font-size:15px;line-height:1.3}.correspondence-lab .ssl-caption{font-size:16px;margin:9px 0}.correspondence-lab .ssl-parameter-controls{margin:7px 0}</style>
