<script setup lang="ts">
import {useId} from 'vue'
withDefaults(defineProps<{stage?:number}>(),{stage:0})
const id=useId()
</script>
<template>
  <svg class="ssl-svg failure-svg" viewBox="0 0 860 282" role="img" aria-label="Faux négatifs, raccourci de fond et recadrage retirant l’anse">
    <defs><marker :id="`${id}-arrow`" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto"><path d="M0 0L10 5L0 10Z" fill="#334155"/></marker></defs>
    <template v-if="stage<2"><text x="167" y="28" text-anchor="middle">Observation enregistrée i = 1</text><text x="684" y="28" text-anchor="middle">Observation enregistrée j = 2</text><foreignObject x="43" y="46" width="248" height="174"><SampleImage/></foreignObject><foreignObject x="560" y="46" width="248" height="174"><SampleImage v-if="stage===0" :sample="1"/><SampleImage v-else false-negative/></foreignObject><path d="M312 128H536" stroke="#c45314" stroke-width="2" stroke-dasharray="6 4"/><text x="425" y="107" text-anchor="middle" class="small">Négatif par indice d’échantillon</text><text x="425" y="175" text-anchor="middle" class="strong">i ≠ j</text><text x="425" y="266" text-anchor="middle">{{stage===0?'L’échantillonnage connaît l’origine de chaque vue.':'Deux enregistrements de la même tasse : faux négatif pour l’identité.'}}</text></template>
    <template v-else-if="stage===2"><text x="122" y="28" text-anchor="middle">Deux vues de i = 1</text><rect x="26" y="48" width="190" height="150" fill="#e8c19f"/><foreignObject x="47" y="68" width="68" height="91"><SampleImage/></foreignObject><foreignObject x="131" y="68" width="68" height="91"><SampleImage :brightness=".85"/></foreignObject><path d="M234 125H301" class="ssl-forward" :marker-end="`url(#${id}-arrow)`"/><rect x="312" y="83" width="218" height="81" rx="4" class="ssl-encoder"/><text x="421" y="113" text-anchor="middle">Encodeur du fond seul</text><text x="421" y="141" text-anchor="middle" class="small">Ignore la tasse</text><path d="M542 125H608" class="ssl-forward" :marker-end="`url(#${id}-arrow)`"/><rect x="620" y="92" width="172" height="63" rx="4" fill="#f9eadc" stroke="#b75b1e"/><text x="706" y="119" text-anchor="middle">Vues en accord</text><text x="706" y="142" text-anchor="middle" class="small">par la couleur du fond</text><text x="425" y="236" text-anchor="middle">Un fond distinctif peut identifier l’enregistrement sans reconnaître l’objet.</text><text x="425" y="263" text-anchor="middle" class="small">Contre-exemple construit · aucune perte expérimentale revendiquée</text></template>
    <template v-else><text x="167" y="28" text-anchor="middle">Original : anse visible</text><text x="684" y="28" text-anchor="middle">Vue transformée : anse absente</text><foreignObject x="43" y="46" width="248" height="174"><SampleImage/></foreignObject><foreignObject x="560" y="46" width="248" height="174"><SampleImage invalid/></foreignObject><path d="M312 128H536" class="ssl-forward" :marker-end="`url(#${id}-arrow)`"/><text x="425" y="106" text-anchor="middle" class="small">Recadrer</text><text x="425" y="260" text-anchor="middle">Tâche : localiser la prise sur l’anse. La vue associée retire les indices nécessaires.</text></template>
  </svg>
  <SSLControls/>
</template>
<style scoped>.failure-svg{height:282px}</style>
