<script setup lang="ts">
import {ref,computed} from 'vue'
const tx=ref(.25),ty=ref(.1),depth=ref(2)
const pos=computed(()=>({x:1.2+2*tx.value/depth.value,y:1.2+2*ty.value/depth.value}))
const valid=computed(()=>pos.value.x>=0&&pos.value.x<3&&pos.value.y>=0&&pos.value.y<3)
const samples=computed(()=>{const i=Math.floor(pos.value.x),j=Math.floor(pos.value.y),a=pos.value.x-i,b=pos.value.y-j;const wx=[1-a,a],wy=[1-b,b];return [{x:i,y:j,w:wx[0]*wy[0]},{x:i+1,y:j,w:wx[1]*wy[0]},{x:i,y:j+1,w:wx[0]*wy[1]},{x:i+1,y:j+1,w:wx[1]*wy[1]}]})
const intensity=(x:number,y:number)=>(x+2*y)/9
const result=computed(()=>samples.value.reduce((s,p)=>s+p.w*intensity(p.x,p.y),0))
const reset=()=>{tx.value=.25;ty.value=.1;depth.value=2}
</script>
<template><div class="demo"><div class="controls"><label>Translation x {{tx.toFixed(2)}}<input aria-label="Translation x" type="range" min="-1" max="1" step=".05" v-model.number="tx"></label><label>Translation y {{ty.toFixed(2)}}<input aria-label="Translation y" type="range" min="-1" max="1" step=".05" v-model.number="ty"></label><label>Profondeur {{depth.toFixed(1)}}<input aria-label="Profondeur" type="range" min=".5" max="4" step=".1" v-model.number="depth"></label><button @click="reset">Réinitialiser</button></div><div class="body"><svg viewBox="0 0 310 280"><g v-for="y in 4" :key="y"><g v-for="x in 4" :key="x"><rect :x="(x-1)*60+35" :y="(y-1)*60+20" width="55" height="55" :fill="`rgb(${255*intensity(x-1,y-1)},${255*intensity(x-1,y-1)},${255*intensity(x-1,y-1)})`"/><text :x="(x-1)*60+62" :y="(y-1)*60+52" text-anchor="middle" :fill="intensity(x-1,y-1)>.5?'black':'white'" style="font-size:13px">{{intensity(x-1,y-1).toFixed(2)}}</text></g></g><circle :cx="pos.x*60+62" :cy="pos.y*60+47" r="7" fill="#CF1C24" stroke="white" stroke-width="2"/></svg><div><p>Position source : ({{pos.x.toFixed(2)}}, {{pos.y.toFixed(2)}})</p><div v-if="valid"><p v-for="(p,i) in samples" :key="i">Pixel ({{p.x}},{{p.y}}) · poids {{p.w.toFixed(3)}}</p><strong>Intensité interpolée : {{result.toFixed(3)}}</strong></div><p v-else class="invalid">Hors domaine : pixel exclu de la perte.</p><p>Caméras sans rotation, focale 2 pixels ; coordonnées aux centres des pixels. Schéma synthétique.</p></div></div></div></template>
<style scoped>.demo{font:16px sans-serif}.controls{display:flex;gap:15px;align-items:center}.controls label{display:grid;gap:3px}.controls input{width:160px;accent-color:#CF1C24}.body{display:grid;grid-template-columns:330px 1fr;gap:25px}svg{height:280px}.body p{margin:8px 0!important}.invalid{color:#CF1C24}button{padding:6px;background:#eee}</style>
