<script setup lang="ts">
import {computed,ref,watch} from 'vue'
import {useNav} from '@slidev/client'
import {depthReference,depthEvaluation} from '../utils/evaluation.mjs'
import {observedTarget,observedSource,descriptorSearch} from '../utils/correspondence.mjs'
import {measurements,cabinetPrediction} from '../utils/interaction.mjs'
const props=withDefaults(defineProps<{stage?:number}>(),{stage:0}),nav=useNav(),scale=ref(1),alignment=ref(false)
const reset=()=>{scale.value=1;alignment.value=props.stage>=1};reset();watch(()=>props.stage,reset)
const factor=computed(()=>nav.isPrintMode.value?1:Number(scale.value)),align=computed(()=>nav.isPrintMode.value?props.stage>=1:alignment.value),depth=computed(()=>depthEvaluation(factor.value,align.value))
const match=descriptorSearch(),predictions=measurements.map((m,i)=>({...m,cost:[.15,.25,.6,.8,.4][i]})),probability=cabinetPrediction(.85,0).probability
const cellColor=(d:number)=>d<3?'#00BDF2':d<5?'#25B34B':'#F15A22'
</script>
<template>
 <div class="task-evaluation" :data-aligned="align" :data-scale="factor" :data-ratio="depth.ratio" :data-absrel="depth.error" :data-depth-prediction="JSON.stringify(depth.prediction)">
  <div class="task-output-grid">
   <div class="task-output"><b>Profondeur</b><div class="metric-definition">AbsRel = mean(|D̂ − D| / D)</div><svg class="ssl-svg depth-samples" viewBox="0 0 350 100" aria-label="Trois profondeurs positives de référence et des prédictions illustrent l’erreur avant/après alignement"><text x="5" y="24" class="small">Référence D</text><text x="5" y="73" class="small">Prédiction D̂</text><g v-for="(d,k) in depthReference" :key="k"><rect :x="130+k*68" y="2" width="62" height="34" :fill="cellColor(d)" fill-opacity=".24"/><text :x="161+k*68" y="25" text-anchor="middle" class="small">{{d}} m</text><rect :x="130+k*68" y="51" width="62" height="34" :fill="cellColor(depth.prediction[k])" fill-opacity=".24"/><text :x="161+k*68" y="74" text-anchor="middle" class="small">{{depth.prediction[k].toFixed(1)}} m</text></g></svg><div class="task-metric">AbsRel : <b>{{depth.error.toFixed(3)}}</b> · {{align?'aligné par médiane':'sans alignement d’échelle'}}</div></div>
   <div class="task-output" :class="{pending:stage<1}"><b>Correspondance</b><svg class="ssl-svg correspondence-output" viewBox="0 0 350 118" aria-label="Requête antérieure fixe et correspondance source au descripteur le plus proche"><text x="72" y="16" text-anchor="middle" class="small">Image requête</text><text x="274" y="16" text-anchor="middle" class="small">Correspondance source</text><foreignObject x="2" y="26" width="140" height="84"><GeoImage :image="observedTarget" label="Image caméra requête" :point="[48,20]"/></foreignObject><foreignObject x="204" y="26" width="140" height="84"><GeoImage :image="observedSource" label="Correspondance de descripteur" :point="match.uv"/></foreignObject><path d="M151 68H192m-9 -5l9 5-9 5" fill="none" stroke="#25B34B" stroke-width="2"/></svg><div class="task-metric">Erreur pixel / rappel sur paires visibles réservées</div></div>
   <div class="task-output" :class="{pending:stage<2}"><b>Traversabilité</b><TerrainImage :samples="predictions"/><div class="task-metric">Erreur de coût sur zones réservées parcourues</div></div>
   <div class="task-output" :class="{pending:stage<3}"><b>Possibilité d’action en manipulation</b><div class="affordance-output"><CabinetScene :show-action="true" :show-labels="false"/><span>Traction à l’anse<br>Ouverture prédite<br>succès : <b>{{probability.toFixed(3)}}</b></span></div><div class="task-metric">Classification ou perte probabiliste sur résultats réservés</div></div>
  </div>
  <div v-if="(align||stage>=1)" class="evaluation-scale-note">L’alignement utilise la profondeur de référence à l’évaluation, sans retrouver l’échelle métrique à l’inférence.</div>
  <div v-if="stage>=3" class="takeaway">Erreur prédictive et succès en boucle fermée répondent à des questions différentes.</div>
  <div v-if="!nav.isPrintMode.value" class="ssl-parameter-controls"><label>Échelle de profondeur <input aria-label="Échelle de profondeur d’évaluation" type="range" min=".5" max="3" step=".5" v-model.number="scale"/>{{scale.toFixed(1)}}</label><label><input aria-label="Aligner la profondeur pour évaluer" type="checkbox" v-model="alignment" @change="($event.target as HTMLElement).blur()"/>Aligner pour l’évaluation</label></div>
  <SSLControls/><div class="ssl-disclosure">Sorties et métriques pédagogiques · descripteurs, coûts et probabilité illustratifs fixes; aucun modèle entraîné</div>
  <div class="citation"><a href="https://github.com/nianticlabs/monodepth2/blob/b017a8164fae339b0ce01f3a9e5048104d5abd0e/evaluate_depth.py">Évaluateur officiel Monodepth2 · AbsRel et échelle médiane monoculaire</a></div>
 </div>
</template>
<style scoped>.task-output-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px 25px;margin:4px 0}.task-output{border-left:3px solid #00BDF2;padding-left:10px;font-size:16px}.task-output b{font-size:16px}.depth-samples,.correspondence-output{height:65px;margin:5px 0}.correspondence-output{height:76px}.correspondence-output .small{font-size:18px}.correspondence-output :deep(.geo-image){margin:0}.correspondence-output :deep(figcaption){display:none}.correspondence-output :deep(canvas){border:0;display:block}.task-output :deep(.terrain-image){height:60px;margin:5px 0}.affordance-output{display:flex;gap:10px;align-items:center;height:60px}.affordance-output :deep(.cabinet-scene){height:60px;width:95px}.affordance-output span{font-size:13px;line-height:1.5}.metric-definition{font-size:12px;margin:3px 0}.task-metric{font-size:14px;min-height:22px;line-height:1.4;margin:4px 0}.pending{opacity:.14}.evaluation-scale-note{font-size:13px;color:#475569;margin:5px 0}.task-evaluation .takeaway{font-size:15px;margin:9px 0;padding:3px 12px}.task-evaluation .ssl-parameter-controls{display:flex;align-items:center;gap:24px;font-size:14px}.task-evaluation .ssl-parameter-controls label{display:flex;align-items:center;gap:7px}.task-evaluation .ssl-disclosure{font-size:11px}.task-evaluation .citation{font-size:11px;margin:4px 0}</style>
